### ISSUE TITLE
Framework error

### ISSUE THREAD

**Issue by 05sonic3valve** [KingOfDog/startup-company-dynamic-products#13]
After starting the game back up I get this error upon loading. This began after installing the mod and creating a custom framework. 

Cannot read property 'pricePerUser' of undefined
TypeError: Cannot read property 'pricePerUser' of undefined
    at _.sum.e.settings.products.map.t (file:///D:/Steam/steamapps/common/Startup%20Company/resources/app/dest/game.min.js:1:1509458)
    at Array.map (<anonymous>)
    at d.e.updateFinanceData (file:///D:/Steam/steamapps/common/Startup%20Company/resources/app/dest/game.min.js:1:1509340)
    at Object.LoadGame (file:///D:/Steam/steamapps/common/Startup%20Company/resources/app/dest/game.min.js:1:1268605)
    at controller.a.loadSaveGame.t [as loadSaveGame] (file:///D:/Steam/steamapps/common/Startup%20Company/resources/app/dest/game.min.js:1:1544999)
    at fn (eval at compile (file:///D:/Steam/steamapps/common/Startup%20Company/resources/app/dest/game.min.js:1:329946), <anonymous>:4:1104)
    at i (file:///D:/Steam/steamapps/common/Startup%20Company/resources/app/dest/game.min.js:1:350376)
    at d.$eval (file:///D:/Steam/steamapps/common/Startup%20Company/resources/app/dest/game.min.js:1:288777)
    at d.$apply (file:///D:/Steam/steamapps/common/Startup%20Company/resources/app/dest/game.min.js:1:289007)
    at HTMLDivElement.<anonymous> (file:///D:/Steam/steamapps/common/Startup%20Company/resources/app/dest/game.min.js:1:350428)

**Comment by KingOfDog** [comment]
Thanks but was already reported (#11) and should be fixed with upcoming update.
